Added try+catch to catch SSL stream error
The exception:

  javax.net.ssl.SSLProtocolException: Data received in non-data state

was happening every few days.  It was totally unexpected and so would
cause the service to shut down.  It is supposedly caused by memory being
prematurely garbage collected, with a corresponding workaround, but it
is difficult to test.  Doing a try+catch is simpler and sufficient.